baseURL = "http://example.org/"
languageCode = "en-us"
title = "DAppLadies"

theme = "reveal-hugo"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
custom_theme = "/robot-lung.css"
